export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_FRIEND_USERNAME = "SET_FRIEND_USERNAME";
export const SET_ACCEPTED_FRIENDSHIP = "SET_ACCEPTED_FRIENDSHIP";
export const SET_MAIN_BANNER_MOVIE = "SET_MAIN_BANNER_MOVIE";

export const GENERICMSG = "GENERICMSG";